version: '3'

services:
  redis:
      image: 'redis:3.2-alpine'
      ports:
        - '6379:6379'
      volumes:
        - 'redis:/data'
  
  web:
    build: '.'
    depends_on:
      - 'redis'
      # environment:
      # FLASK_DEBUG: 'true'
    env_file:
      - '.env'
        #image: 'anildiwan76/web1'
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
volumes:
  redis: {}